### ISSUE TITLE
Route of app-name.domain is always created, even if a different route is given

### ISSUE THREAD

**Issue by oppegard** [cloudfoundry-incubator/push-apps#16]
Given something like:

```yaml
apps:
- name: some-name
  domain: example.com
  route:
    hostname: lemons
```
Two routes will be created:
- lemons.example.com
- some-name.example.com

The desired behavior is that only `lemons.example.com` is created. This more easily allows multiple apps with the same name on a CF to exist. For example, I can have app `some-name` in space1 and also app `some-name` in space2, but with different, non-clashing routes.
